-- ============================================================
-- FinTrack Personal Finance Management System
-- Database Schema V1 - Initial
-- ============================================================

-- ==================== USERS ====================
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255)    NOT NULL UNIQUE,
    password_hash   VARCHAR(255)    NOT NULL,
    full_name       VARCHAR(100)    NOT NULL,
    phone           VARCHAR(20),
    avatar_url      VARCHAR(500),
    default_currency VARCHAR(3)     NOT NULL DEFAULT 'USD',
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_users_email ON users(email);

-- ==================== CATEGORIES ====================
CREATE TABLE categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    name            VARCHAR(100)    NOT NULL,
    icon            VARCHAR(50),
    color           VARCHAR(7),
    type            VARCHAR(20)     NOT NULL, -- INCOME, EXPENSE, BOTH
    is_system       BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_categories_user ON categories(user_id);

-- ==================== ACCOUNTS ====================
CREATE TABLE accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    name            VARCHAR(100)    NOT NULL,
    type            VARCHAR(20)     NOT NULL, -- CARD, CASH, ACCOUNT, SAVINGS, INVESTMENT
    currency        VARCHAR(3)      NOT NULL DEFAULT 'USD',
    balance         DECIMAL(19,4)   NOT NULL DEFAULT 0.0000,
    initial_balance DECIMAL(19,4)   NOT NULL DEFAULT 0.0000,
    icon            VARCHAR(50),
    color           VARCHAR(7),
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    version         BIGINT          NOT NULL DEFAULT 0, -- Optimistic locking
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_accounts_user ON accounts(user_id);
CREATE INDEX idx_accounts_user_active ON accounts(user_id, is_active);

-- ==================== TRANSACTIONS ====================
CREATE TABLE transactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    account_id      BIGINT          NOT NULL,
    category_id     BIGINT,
    type            VARCHAR(20)     NOT NULL, -- INCOME, EXPENSE, TRANSFER_IN, TRANSFER_OUT
    amount          DECIMAL(19,4)   NOT NULL,
    description     VARCHAR(500),
    note            VARCHAR(1000),
    transaction_date DATE           NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted       BOOLEAN         NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_transactions_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT chk_transactions_amount CHECK (amount > 0)
);

CREATE INDEX idx_transactions_user ON transactions(user_id);
CREATE INDEX idx_transactions_account ON transactions(account_id);
CREATE INDEX idx_transactions_date ON transactions(transaction_date);
CREATE INDEX idx_transactions_type ON transactions(type);
CREATE INDEX idx_transactions_user_date ON transactions(user_id, transaction_date);
CREATE INDEX idx_transactions_user_type_date ON transactions(user_id, type, transaction_date);
CREATE INDEX idx_transactions_category ON transactions(category_id);

-- ==================== TRANSFER RECORDS ====================
CREATE TABLE transfer_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT          NOT NULL,
    source_account_id   BIGINT          NOT NULL,
    target_account_id   BIGINT          NOT NULL,
    source_amount       DECIMAL(19,4)   NOT NULL,
    target_amount       DECIMAL(19,4)   NOT NULL,
    exchange_rate       DECIMAL(19,6),
    source_currency     VARCHAR(3)      NOT NULL,
    target_currency     VARCHAR(3)      NOT NULL,
    description         VARCHAR(500),
    idempotency_key     VARCHAR(64)     UNIQUE,
    source_transaction_id BIGINT,
    target_transaction_id BIGINT,
    transfer_date       DATE            NOT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transfers_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_transfers_source FOREIGN KEY (source_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_transfers_target FOREIGN KEY (target_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_transfers_source_tx FOREIGN KEY (source_transaction_id) REFERENCES transactions(id),
    CONSTRAINT fk_transfers_target_tx FOREIGN KEY (target_transaction_id) REFERENCES transactions(id)
);

CREATE INDEX idx_transfers_user ON transfer_records(user_id);
CREATE INDEX idx_transfers_idempotency ON transfer_records(idempotency_key);

-- ==================== DEBTS & RECEIVABLES ====================
CREATE TABLE debts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    type            VARCHAR(20)     NOT NULL, -- DEBT (I owe), RECEIVABLE (owed to me)
    person_name     VARCHAR(200)    NOT NULL,
    amount          DECIMAL(19,4)   NOT NULL,
    currency        VARCHAR(3)      NOT NULL DEFAULT 'USD',
    description     VARCHAR(500),
    due_date        DATE,
    status          VARCHAR(20)     NOT NULL DEFAULT 'OPEN', -- OPEN, CLOSED, OVERDUE
    closed_at       TIMESTAMP,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted      BOOLEAN         NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_debts_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_debts_amount CHECK (amount > 0)
);

CREATE INDEX idx_debts_user ON debts(user_id);
CREATE INDEX idx_debts_status ON debts(status);
CREATE INDEX idx_debts_due_date ON debts(due_date);

-- ==================== BUDGETS ====================
CREATE TABLE budgets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    category_id     BIGINT,
    name            VARCHAR(100)    NOT NULL,
    amount_limit    DECIMAL(19,4)   NOT NULL,
    currency        VARCHAR(3)      NOT NULL DEFAULT 'USD',
    period_type     VARCHAR(20)     NOT NULL DEFAULT 'MONTHLY', -- WEEKLY, MONTHLY, YEARLY
    start_date      DATE            NOT NULL,
    end_date        DATE,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_budgets_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT chk_budgets_limit CHECK (amount_limit > 0)
);

CREATE INDEX idx_budgets_user ON budgets(user_id);
CREATE INDEX idx_budgets_active ON budgets(user_id, is_active);

-- ==================== AUDIT LOGS ====================
CREATE TABLE audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    entity_type     VARCHAR(50)     NOT NULL,
    entity_id       BIGINT          NOT NULL,
    action          VARCHAR(20)     NOT NULL, -- CREATE, UPDATE, DELETE, TRANSFER
    old_value       TEXT,
    new_value       TEXT,
    ip_address      VARCHAR(45),
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_audit_user ON audit_logs(user_id);
CREATE INDEX idx_audit_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_logs(created_at);

-- ==================== NOTIFICATIONS ====================
CREATE TABLE notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    type            VARCHAR(50)     NOT NULL, -- BUDGET_WARNING, BUDGET_EXCEEDED, ANOMALY, BILL_REMINDER, SYSTEM
    title           VARCHAR(200)    NOT NULL,
    message         VARCHAR(1000)   NOT NULL,
    is_read         BOOLEAN         NOT NULL DEFAULT FALSE,
    metadata        TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_notifications_user ON notifications(user_id);
CREATE INDEX idx_notifications_unread ON notifications(user_id, is_read);

-- ==================== AI CATEGORY RULES ====================
CREATE TABLE ai_category_rules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    keyword         VARCHAR(100)    NOT NULL,
    category_id     BIGINT          NOT NULL,
    confidence      DECIMAL(3,2)    NOT NULL DEFAULT 1.00,
    is_system       BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ai_rules_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ai_rules_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE INDEX idx_ai_rules_keyword ON ai_category_rules(keyword);
CREATE INDEX idx_ai_rules_user ON ai_category_rules(user_id);

-- ==================== EXCHANGE RATES ====================
CREATE TABLE exchange_rates (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_currency VARCHAR(3)      NOT NULL,
    target_currency VARCHAR(3)      NOT NULL,
    rate            DECIMAL(19,6)   NOT NULL,
    fetched_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_exchange_rates_pair ON exchange_rates(source_currency, target_currency);

-- ==================== FAMILY GROUPS ====================
CREATE TABLE family_groups (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    owner_id        BIGINT          NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_family_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

-- ==================== FAMILY MEMBERS ====================
CREATE TABLE family_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    role            VARCHAR(20)     NOT NULL DEFAULT 'MEMBER', -- OWNER, MEMBER
    joined_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_family_members_group FOREIGN KEY (group_id) REFERENCES family_groups(id),
    CONSTRAINT fk_family_members_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_family_member UNIQUE (group_id, user_id)
);

-- ==================== SHARED ACCOUNTS ====================
CREATE TABLE shared_accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT          NOT NULL,
    account_id      BIGINT          NOT NULL,
    shared_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_shared_group FOREIGN KEY (group_id) REFERENCES family_groups(id),
    CONSTRAINT fk_shared_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT uk_shared_account UNIQUE (group_id, account_id)
);

-- ==================== REFRESH TOKENS ====================
CREATE TABLE refresh_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    token           VARCHAR(500)    NOT NULL UNIQUE,
    expires_at      TIMESTAMP       NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);
