-- ==================== REMINDERS ====================
CREATE TABLE reminders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    description     VARCHAR(500)    NOT NULL,
    amount          DECIMAL(19,4),
    currency        VARCHAR(3),
    reminder_date   DATE            NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reminders_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_reminders_user_date ON reminders(user_id, reminder_date);
