CREATE TABLE cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    license_plate VARCHAR(20) NOT NULL,
    registration_certificate VARCHAR(50),
    nickname VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cars_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE fines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id BIGINT NOT NULL,
    violation_type VARCHAR(100) NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    fine_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fines_car FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE CASCADE
);

-- ============================================================
-- Demo Car & Fines Seed Data (user_id = 1000)
-- ============================================================

INSERT INTO cars (id, user_id, license_plate, registration_certificate, nickname) VALUES
(1001, 1000, '01 A 777 BC', 'AAB1234567', 'Family SUV'),
(1002, 1000, '01 X 555 DA', NULL, 'City Sedan');

INSERT INTO fines (id, car_id, violation_type, amount, fine_date, status, paid_at) VALUES
(1, 1001, 'Speeding - 20 km/h over limit',    150.0000, '2026-02-05', 'UNPAID', NULL),
(2, 1001, 'Red light violation',               300.0000, '2026-02-18', 'UNPAID', NULL),
(3, 1001, 'Illegal parking',                    75.0000, '2026-01-10', 'PAID',   '2026-01-15 10:30:00'),
(4, 1002, 'Speeding - 40 km/h over limit',    500.0000, '2026-03-02', 'UNPAID', NULL),
(5, 1002, 'Seatbelt violation',                 50.0000, '2026-02-20', 'PAID',   '2026-02-25 14:00:00'),
(6, 1002, 'Expired registration',              200.0000, '2026-03-08', 'UNPAID', NULL);
